=== Edelstadt/List-of-saints-template/saints.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:attribute name="important">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="primary"/>
				<xs:pattern value="secondary"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="sources" type="xs:string"/>
	<xs:element name="root">
		<xs:complexType>
			<xs:all>
				<xs:element name="source"><!--zdroj čerpání dat (možná lepší u každé položky ?)-->
					<xs:complexType>
						<xs:all>
							<xs:element name="url"><!--třeba web-->
								<xs:complexType>
									<xs:sequence>
										<xs:element name="author" nillable="true">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="surname" type="xs:string"/>
													<xs:element name="name" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="page_title" type="xs:string"/>
										<xs:element name="web_title" type="xs:string"/>
										<xs:element name="addrese" type="xs:anyURI"/>
										<xs:element name="date_visit" type="xs:date" nillable="true"/>
										<xs:element name="date_citation" type="xs:date"/>
									</xs:sequence>
									<xs:attribute name="id" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="book"><!--nebo kniha (isbn méně vhodné s přihlédnutím ke starším tiskům-->
								<xs:complexType>
									<xs:sequence>
										<xs:element name="author" maxOccurs="4">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="surname" type="xs:string"/>
													<xs:element name="name" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="isbn" type="xs:nonNegativeInteger"/>
										<xs:element name="publication_title" type="xs:string"/>
										<xs:element name="place_issue" type="xs:string"/>
										<xs:element name="publisher" type="xs:string"/>
										<xs:element name="year_publication" type="xs:short"/>
									</xs:sequence>
									<xs:attribute name="id" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="articles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="article" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:gMonthDay">
														<xs:attribute ref="important" default="primary"/>
														<xs:attribute name="sources" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="name" maxOccurs="10"><!--jméno svátku min. v jednom jazyce, max. v 10 (?)-->
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="lang" type="xs:language"/>
														<xs:attribute name="sources" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="since" nillable="true"><!--rok od kdy se slaví (výběr rok nebo století)-->
											<xs:complexType>
												<xs:choice>
													<xs:element name="year">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:gYear">
																	<xs:attribute name="sources" type="xs:string"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="century">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:positiveInteger">
																	<xs:attribute name="sources" type="xs:string"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:element name="until" nillable="true"><!--některé už se slavit přestaly-->
											<xs:complexType>
												<xs:choice>
													<xs:element name="year">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:gYear">
																	<xs:attribute name="sources" type="xs:string"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="century">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:positiveInteger">
																	<xs:attribute name="sources" type="xs:string"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:element name="venerated" maxOccurs="10">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="sources" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="significant_in" nillable="true">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="sources" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="comment" type="xs:string" nillable="true"/><!--komentáře, životopis, zajímavost ?-->
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Edelstadt/List-of-saints-template/example.xml
<?xml version="1.0" encoding="UTF-8"?>

<articles xsi:noNamespaceSchemaLocation="saints.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<article>
		<date important="primary">--12-06</date>
		<name lang="CS">Mikuláš</name>
		<name lang="DE" sources="0002">Nikolaus von Myra</name>
		<since>
			<century>8</century>
		</since>
		<until xsi:nil="true"/>
		<venerated>cat</venerated>
		<significant_in xsi:nil="true"/>
		<source>
			<url id="0002">
				<author xsi:nil="true"/>
				<page_title>Nikolaus von Myra</page_title>
				<web_title>Wikipedia</web_title>
				<addrese>https://de.wikipedia.org/wiki/Nikolaus_von_Myra</addrese>
				<date_visit>2016-03-21</date_visit>
				<date_citation>2016-03-21</date_citation>
			</url>
		</source>
		<source>
			<book id="0001">
				<author>
					<surname>Bláhová</surname>
					<name>Marie</name>
				</author>
				<isbn>8072770241</isbn>
				<publication_title>Historická chronologie</publication_title>
				<place_issue>Praha</place_issue>
				<publisher>LIBRI</publisher>
				<year_publication>2001</year_publication>
			</book>
		</source>
		<comment/>
	</article>
</articles>
